default: &default
  adapter: postgresql
  encoding: unicode
  # of course a proper username and password saved in environment variables would be required for a real project
  # username: postgres
  # password: xxxxx #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nps_development

test:
  <<: *default
  database: nps_test

production:
  <<: *default
  database: nps_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
